// src/main/webapp/app/entities/products/recipe/update/recipe-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize } from 'rxjs/operators';

import { IRecipe, Recipe } from '../recipe.model';
import { RecipeService } from '../service/recipe.service';

@Component({
  selector: 'jhi-recipe-update',
  templateUrl: './recipe-update.component.html',
})
export class RecipeUpdateComponent implements OnInit {
  isSaving = false;

  editForm = this.fb.group({
    id: [],
    name: [null, [Validators.required]],
    instructionsBody: [null, [Validators.required]],
  });

  constructor(protected recipeService: RecipeService, protected activatedRoute: ActivatedRoute, protected fb: FormBuilder) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ recipe }) => {
      this.updateForm(recipe);
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const recipe = this.createFromForm();
    if (recipe.id !== undefined) {
      this.subscribeToSaveResponse(this.recipeService.update(recipe));
    } else {
      this.subscribeToSaveResponse(this.recipeService.create(recipe));
    }
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IRecipe>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(recipe: IRecipe): void {
    this.editForm.patchValue({
      id: recipe.id,
      name: recipe.name,
      instructionsBody: recipe.instructionsBody,
    });
  }

  protected createFromForm(): IRecipe {
    return {
      ...new Recipe(),
      id: this.editForm.get(['id'])!.value,
      name: this.editForm.get(['name'])!.value,
      instructionsBody: this.editForm.get(['instructionsBody'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-recipe-heading" data-cy="RecipeCreateUpdateHeading" jhiTranslate="gatewayApp.productsRecipe.home.createOrEditLabel">
        Create or edit a Recipe
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="gatewayApp.productsRecipe.name" for="field_name">Name</label>
          <input type="text" class="form-control" name="name" id="field_name" data-cy="name" formControlName="name" />
          <div *ngIf="editForm.get('name')!.invalid && (editForm.get('name')!.dirty || editForm.get('name')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('name')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="gatewayApp.productsRecipe.instructionsBody" for="field_instructionsBody"
            >Instructions Body</label
          >
          <input
            type="text"
            class="form-control"
            name="instructionsBody"
            id="field_instructionsBody"
            data-cy="instructionsBody"
            formControlName="instructionsBody"
          />
          <div
            *ngIf="
              editForm.get('instructionsBody')!.invalid &&
              (editForm.get('instructionsBody')!.dirty || editForm.get('instructionsBody')!.touched)
            "
          >
            <small
              class="form-text text-danger"
              *ngIf="editForm.get('instructionsBody')?.errors?.required"
              jhiTranslate="entity.validation.required"
            >
              This field is required.
            </small>
          </div>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>

// src/main/webapp/app/entities/products/recipe/recipe-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="gatewayApp.productsRecipe.home.createOrEditLabel"
          data-cy="RecipeCreateUpdateHeading"
          v-text="$t('gatewayApp.productsRecipe.home.createOrEditLabel')"
        >
          Create or edit a Recipe
        </h2>
        <div>
          <div class="form-group" v-if="recipe.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="recipe.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('gatewayApp.productsRecipe.name')" for="recipe-name">Name</label>
            <input
              type="text"
              class="form-control"
              name="name"
              id="recipe-name"
              data-cy="name"
              :class="{ valid: !$v.recipe.name.$invalid, invalid: $v.recipe.name.$invalid }"
              v-model="$v.recipe.name.$model"
              required
            />
            <div v-if="$v.recipe.name.$anyDirty && $v.recipe.name.$invalid">
              <small class="form-text text-danger" v-if="!$v.recipe.name.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('gatewayApp.productsRecipe.instructionsBody')" for="recipe-instructionsBody"
              >Instructions Body</label
            >
            <input
              type="text"
              class="form-control"
              name="instructionsBody"
              id="recipe-instructionsBody"
              data-cy="instructionsBody"
              :class="{ valid: !$v.recipe.instructionsBody.$invalid, invalid: $v.recipe.instructionsBody.$invalid }"
              v-model="$v.recipe.instructionsBody.$model"
              required
            />
            <div v-if="$v.recipe.instructionsBody.$anyDirty && $v.recipe.instructionsBody.$invalid">
              <small class="form-text text-danger" v-if="!$v.recipe.instructionsBody.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('gatewayApp.productsRecipe.user')" for="recipe-user">User</label>
            <select class="form-control" id="recipe-user" data-cy="user" name="user" v-model="recipe.user">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="recipe.user && userOption.id === recipe.user.id ? recipe.user : userOption"
                v-for="userOption in users"
                :key="userOption.id"
              >
                {{ userOption.login }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.recipe.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./recipe-update.component.ts"></script>
