// src/main/webapp/app/entities/products/product/product-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" role="form" novalidate v-on:submit.prevent="save()">
        <h2
          id="gatewayApp.productsProduct.home.createOrEditLabel"
          data-cy="ProductCreateUpdateHeading"
          v-text="$t('gatewayApp.productsProduct.home.createOrEditLabel')"
        >
          Create or edit a Product
        </h2>
        <div>
          <div class="form-group" v-if="product.id">
            <label for="id" v-text="$t('global.field.id')">ID</label>
            <input type="text" class="form-control" id="id" name="id" v-model="product.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('gatewayApp.productsProduct.name')" for="product-name">Name</label>
            <input
              type="text"
              class="form-control"
              name="name"
              id="product-name"
              data-cy="name"
              :class="{ valid: !$v.product.name.$invalid, invalid: $v.product.name.$invalid }"
              v-model="$v.product.name.$model"
              required
            />
            <div v-if="$v.product.name.$anyDirty && $v.product.name.$invalid">
              <small class="form-text text-danger" v-if="!$v.product.name.required" v-text="$t('entity.validation.required')">
                This field is required.
              </small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('gatewayApp.productsProduct.eanCode')" for="product-eanCode">Ean Code</label>
            <input
              type="text"
              class="form-control"
              name="eanCode"
              id="product-eanCode"
              data-cy="eanCode"
              :class="{ valid: !$v.product.eanCode.$invalid, invalid: $v.product.eanCode.$invalid }"
              v-model="$v.product.eanCode.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('gatewayApp.productsProduct.productCategory')" for="product-productCategory"
              >Product Category</label
            >
            <select
              class="form-control"
              id="product-productCategory"
              data-cy="productCategory"
              name="productCategory"
              v-model="product.productCategory"
            >
              <option v-bind:value="null"></option>
              <option
                v-bind:value="
                  product.productCategory && productCategoryOption.id === product.productCategory.id
                    ? product.productCategory
                    : productCategoryOption
                "
                v-for="productCategoryOption in productCategories"
                :key="productCategoryOption.id"
              >
                {{ productCategoryOption.id }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="$t('gatewayApp.productsProduct.productUnit')" for="product-productUnit"
              >Product Unit</label
            >
            <select class="form-control" id="product-productUnit" data-cy="productUnit" name="productUnit" v-model="product.productUnit">
              <option v-bind:value="null"></option>
              <option
                v-bind:value="
                  product.productUnit && productUnitOption.id === product.productUnit.id ? product.productUnit : productUnitOption
                "
                v-for="productUnitOption in productUnits"
                :key="productUnitOption.id"
              >
                {{ productUnitOption.id }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" class="btn btn-secondary" v-on:click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.cancel')">Cancel</span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="$v.product.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="$t('entity.action.save')">Save</span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./product-update.component.ts"></script>

// src/main/webapp/app/entities/products/product/update/product-update.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpResponse } from '@angular/common/http';
import { FormBuilder, Validators } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { Observable } from 'rxjs';
import { finalize, map } from 'rxjs/operators';

import { IProduct, Product } from '../product.model';
import { ProductService } from '../service/product.service';
import { IProductUnit } from 'app/entities/products/product-unit/product-unit.model';
import { ProductUnitService } from 'app/entities/products/product-unit/service/product-unit.service';
import { IProductCategory } from 'app/entities/products/product-category/product-category.model';
import { ProductCategoryService } from 'app/entities/products/product-category/service/product-category.service';

@Component({
  selector: 'jhi-product-update',
  templateUrl: './product-update.component.html',
})
export class ProductUpdateComponent implements OnInit {
  isSaving = false;

  productUnitsSharedCollection: IProductUnit[] = [];
  productCategoriesSharedCollection: IProductCategory[] = [];

  editForm = this.fb.group({
    id: [],
    name: [null, [Validators.required]],
    eanCode: [],
    productUnits: [],
    productCategory: [],
  });

  constructor(
    protected productService: ProductService,
    protected productUnitService: ProductUnitService,
    protected productCategoryService: ProductCategoryService,
    protected activatedRoute: ActivatedRoute,
    protected fb: FormBuilder
  ) {}

  ngOnInit(): void {
    this.activatedRoute.data.subscribe(({ product }) => {
      this.updateForm(product);

      this.loadRelationshipsOptions();
    });
  }

  previousState(): void {
    window.history.back();
  }

  save(): void {
    this.isSaving = true;
    const product = this.createFromForm();
    if (product.id !== undefined) {
      this.subscribeToSaveResponse(this.productService.update(product));
    } else {
      this.subscribeToSaveResponse(this.productService.create(product));
    }
  }

  trackProductUnitById(index: number, item: IProductUnit): number {
    return item.id!;
  }

  trackProductCategoryById(index: number, item: IProductCategory): number {
    return item.id!;
  }

  getSelectedProductUnit(option: IProductUnit, selectedVals?: IProductUnit[]): IProductUnit {
    if (selectedVals) {
      for (const selectedVal of selectedVals) {
        if (option.id === selectedVal.id) {
          return selectedVal;
        }
      }
    }
    return option;
  }

  protected subscribeToSaveResponse(result: Observable<HttpResponse<IProduct>>): void {
    result.pipe(finalize(() => this.onSaveFinalize())).subscribe(
      () => this.onSaveSuccess(),
      () => this.onSaveError()
    );
  }

  protected onSaveSuccess(): void {
    this.previousState();
  }

  protected onSaveError(): void {
    // Api for inheritance.
  }

  protected onSaveFinalize(): void {
    this.isSaving = false;
  }

  protected updateForm(product: IProduct): void {
    this.editForm.patchValue({
      id: product.id,
      name: product.name,
      eanCode: product.eanCode,
      productUnits: product.productUnits,
      productCategory: product.productCategory,
    });

    this.productUnitsSharedCollection = this.productUnitService.addProductUnitToCollectionIfMissing(
      this.productUnitsSharedCollection,
      ...(product.productUnits ?? [])
    );
    this.productCategoriesSharedCollection = this.productCategoryService.addProductCategoryToCollectionIfMissing(
      this.productCategoriesSharedCollection,
      product.productCategory
    );
  }

  protected loadRelationshipsOptions(): void {
    this.productUnitService
      .query()
      .pipe(map((res: HttpResponse<IProductUnit[]>) => res.body ?? []))
      .pipe(
        map((productUnits: IProductUnit[]) =>
          this.productUnitService.addProductUnitToCollectionIfMissing(productUnits, ...(this.editForm.get('productUnits')!.value ?? []))
        )
      )
      .subscribe((productUnits: IProductUnit[]) => (this.productUnitsSharedCollection = productUnits));

    this.productCategoryService
      .query()
      .pipe(map((res: HttpResponse<IProductCategory[]>) => res.body ?? []))
      .pipe(
        map((productCategories: IProductCategory[]) =>
          this.productCategoryService.addProductCategoryToCollectionIfMissing(
            productCategories,
            this.editForm.get('productCategory')!.value
          )
        )
      )
      .subscribe((productCategories: IProductCategory[]) => (this.productCategoriesSharedCollection = productCategories));
  }

  protected createFromForm(): IProduct {
    return {
      ...new Product(),
      id: this.editForm.get(['id'])!.value,
      name: this.editForm.get(['name'])!.value,
      eanCode: this.editForm.get(['eanCode'])!.value,
      productUnits: this.editForm.get(['productUnits'])!.value,
      productCategory: this.editForm.get(['productCategory'])!.value,
    };
  }
}

<div class="row justify-content-center">
  <div class="col-8">
    <form name="editForm" role="form" novalidate (ngSubmit)="save()" [formGroup]="editForm">
      <h2 id="jhi-product-heading" data-cy="ProductCreateUpdateHeading" jhiTranslate="gatewayApp.productsProduct.home.createOrEditLabel">
        Create or edit a Product
      </h2>

      <div>
        <jhi-alert-error></jhi-alert-error>

        <div class="form-group" [hidden]="editForm.get('id')!.value == null">
          <label class="form-control-label" jhiTranslate="global.field.id" for="field_id">ID</label>
          <input type="number" class="form-control" name="id" id="field_id" data-cy="id" formControlName="id" [readonly]="true" />
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="gatewayApp.productsProduct.name" for="field_name">Name</label>
          <input type="text" class="form-control" name="name" id="field_name" data-cy="name" formControlName="name" />
          <div *ngIf="editForm.get('name')!.invalid && (editForm.get('name')!.dirty || editForm.get('name')!.touched)">
            <small class="form-text text-danger" *ngIf="editForm.get('name')?.errors?.required" jhiTranslate="entity.validation.required">
              This field is required.
            </small>
          </div>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="gatewayApp.productsProduct.eanCode" for="field_eanCode">Ean Code</label>
          <input type="text" class="form-control" name="eanCode" id="field_eanCode" data-cy="eanCode" formControlName="eanCode" />
        </div>

        <div class="form-group">
          <label jhiTranslate="gatewayApp.productsProduct.productUnit" for="field_productUnits">Product Unit</label>
          <select
            class="form-control"
            id="field_productUnits"
            data-cy="productUnit"
            multiple
            name="productUnits"
            formControlName="productUnits"
          >
            <option
              [ngValue]="getSelectedProductUnit(productUnitOption, editForm.get('productUnits')!.value)"
              *ngFor="let productUnitOption of productUnitsSharedCollection; trackBy: trackProductUnitById"
            >
              {{ productUnitOption.id }}
            </option>
          </select>
        </div>

        <div class="form-group">
          <label class="form-control-label" jhiTranslate="gatewayApp.productsProduct.productCategory" for="field_productCategory"
            >Product Category</label
          >
          <select
            class="form-control"
            id="field_productCategory"
            data-cy="productCategory"
            name="productCategory"
            formControlName="productCategory"
          >
            <option [ngValue]="null"></option>
            <option
              [ngValue]="
                productCategoryOption.id === editForm.get('productCategory')!.value?.id
                  ? editForm.get('productCategory')!.value
                  : productCategoryOption
              "
              *ngFor="let productCategoryOption of productCategoriesSharedCollection; trackBy: trackProductCategoryById"
            >
              {{ productCategoryOption.id }}
            </option>
          </select>
        </div>
      </div>

      <div>
        <button type="button" id="cancel-save" class="btn btn-secondary" (click)="previousState()">
          <fa-icon icon="ban"></fa-icon>&nbsp;<span jhiTranslate="entity.action.cancel">Cancel</span>
        </button>

        <button
          type="submit"
          id="save-entity"
          data-cy="entityCreateSaveButton"
          [disabled]="editForm.invalid || isSaving"
          class="btn btn-primary"
        >
          <fa-icon icon="save"></fa-icon>&nbsp;<span jhiTranslate="entity.action.save">Save</span>
        </button>
      </div>
    </form>
  </div>
</div>
